# Generated by Django 4.2.2 on 2023-11-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0002_alter_department_tests_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='tests_scope',
            field=models.ManyToManyField(blank=True, to='laboratories.test'),
        ),
    ]
