# Generated by Django 4.2.2 on 2023-11-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0003_alter_department_tests_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='subscribe_for_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lab',
            name='subscription_duration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='subscription_key',
            field=models.CharField(default='dnuir8', max_length=10),
            preserve_default=False,
        ),
    ]
