# Generated by Django 4.2.2 on 2023-11-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0004_lab_subscribe_for_premium_lab_subscription_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
