# Generated by Django 4.2.2 on 2023-11-06 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratories', '0001_initial'),
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('hospital_name', models.CharField(max_length=200)),
                ('acreditation_code', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='hospitals/logos')),
                ('digital_address', models.CharField(max_length=200)),
                ('region_of_location', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=150)),
                ('head_of_ward', models.CharField(max_length=100)),
                ('conact', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_on', models.DateField(default=django.utils.timezone.now)),
                ('send_by', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('sample_type', models.CharField(max_length=200)),
                ('sample_tube', models.CharField(max_length=50)),
                ('sample_id', models.CharField(max_length=100)),
                ('sample_origin', models.CharField(max_length=100)),
                ('sex_of_client', models.CharField(max_length=10)),
                ('name_of_client', models.CharField(max_length=100)),
                ('age_of_client', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('received_by', models.CharField(max_length=150)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.delivery')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.lab')),
                ('test_to_be_done', models.ManyToManyField(to='laboratories.test')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.ward')),
            ],
        ),
    ]
