# Generated by Django 4.2.2 on 2023-11-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='conact',
            new_name='contact',
        ),
    ]
