# Generated by Django 4.2.2 on 2023-11-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0004_lab_subscribe_for_premium_lab_subscription_duration_and_more'),
        ('patients', '0002_patient_age_patient_hospital_patient_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tests',
            field=models.ManyToManyField(blank=True, to='laboratories.test'),
        ),
    ]
